name: docs

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 1.8
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Publish docs
        env:
          GH_TOKEN: ${{ secrets.MICROSITE_TOKEN }}
        run: |
          mkdir docs/docs
          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"
          gem install jekyll bundler
          csbt docs/publishMicrosite
