name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 14
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.14
      - name: Cache Coursier
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v2.1.4
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      # - name: Checking your code format
      #   run: |
      #     csbt scalafmtCheckAll
      - name: Run test
        run: csbt clean +scalajavatimeTestsJVM/test +scalajavatimeTestsJS/test +demo/run
