name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.14
      - name: Cache Coursier
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v2.1.3
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Checking your code format
        run: |
          java -version
          csbt scalafmtCheckAll
      - name: Run test
        run: csbt clean +scalajavatimeTestsJVM/test +scalajavatimeTestsJS/test demo/run
      - name: Run test 0.6
        run: SCALAJS_VERSION=0.6.33 csbt clean +scalajavatimeTestsJS/fastOptJS
